# Generated by Django 3.1.7 on 2021-03-26 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Post title')),
                ('description', models.TextField(verbose_name='Post description')),
                ('featured', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_increase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('town', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=5)),
                ('condition', models.CharField(max_length=150, verbose_name='Car Condition')),
                ('seller_type', models.CharField(max_length=150, verbose_name='Seller Type')),
                ('make', models.CharField(max_length=150, verbose_name='Car Make')),
                ('model', models.CharField(max_length=150, verbose_name='Car Model')),
                ('variant', models.CharField(max_length=150, verbose_name='Car Variant')),
                ('badge', models.CharField(max_length=150, verbose_name='Car Badge')),
                ('odometer', models.IntegerField(verbose_name='Car Odometer')),
                ('year', models.CharField(max_length=4, verbose_name='Car Year')),
                ('model_year', models.CharField(max_length=4, verbose_name='Car Model Year')),
                ('engine', models.CharField(max_length=50, verbose_name='Car Engine')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='Car Fuel Type')),
                ('drive_type', models.CharField(max_length=50, verbose_name='Car Drive Type')),
                ('exterior_color', models.CharField(max_length=50, verbose_name='Car Exterior Color')),
                ('interior_color', models.CharField(max_length=50, verbose_name='Car Interior color')),
                ('transmission', models.CharField(max_length=150, verbose_name='Car Transmission')),
                ('body_type', models.CharField(max_length=150, verbose_name='Car Body Type')),
                ('seats', models.CharField(max_length=10, verbose_name='Car Seats')),
                ('reg_exp', models.DateField()),
                ('vin', models.CharField(max_length=250, verbose_name='Car VIN')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='post_images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post')),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='post_post_user_id_57d352_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['post'], name='post_image_post_id_4c6280_idx'),
        ),
    ]
