# Generated by Django 3.1.7 on 2021-04-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0003_auto_20210330_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='reg_exp',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_time',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='vin',
            field=models.CharField(blank=True, max_length=250, verbose_name='Car VIN'),
        ),
    ]
